### ISSUE TITLE
Install/import of `imgurpython.client.ImgurClient` of package failes.

### ISSUE THREAD

**Issue by luckydonald** [luckydonald/luckydonald-utils#2]
``` python
>>> ImgurClient = import_or_install("imgurpython.client.ImgurClient")
Traceback (most recent call last):
  File "/home/luckydonald/software/bonbot/virtualenv_py3.4/lib/python3.4/site-packages/luckydonaldUtils/dependencies.py", line 59, in import_only
    imp = importlib.import_module(package_name)
  File "/home/luckydonald/software/bonbot/virtualenv_py3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'imgurpython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luckydonald/software/bonbot/virtualenv_py3.4/lib/python3.4/site-packages/luckydonaldUtils/dependencies.py", line 34, in import_or_install
    imp = import_only(package_name)
  File "/home/luckydonald/software/bonbot/virtualenv_py3.4/lib/python3.4/site-packages/luckydonaldUtils/dependencies.py", line 74, in import_only
    imp = importlib.import_module(package_name, package=module_list)
  File "/home/luckydonald/software/bonbot/virtualenv_py3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2249, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2199, in _sanity_check
SystemError: Parent module 'ImgurClient' not loaded, cannot perform relative import
```

**Comment by luckydonald** [comment]
https://bugs.python.org/issue18018
