### ISSUE TITLE
ImportError: No module named 'pip.utils'

### ISSUE THREAD

**Issue by luckydonald** [luckydonald/luckydonald-utils#3]
https://github.com/luckydonald/pytg/issues/78

> Install issue was just solved by removing python 3.4 and installing 3.5.1 with pip 8.1.1.
> It looks like issue was cause by old pip version.

``` shell
Processing luckydonald-utils-0.43.tar.gz
Writing /tmp/easy_install-3gup5eno/luckydonald-utils-0.43/setup.cfg
Running luckydonald-utils-0.43/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3gup5eno/luckydonald-utils-0.43/egg-dist-tmp-djhzz5ae
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    install_requires=["DictObject", "luckydonald-utils>=0.17"]
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/usr/lib/python3/dist-packages/setuptools/compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 4, in <module>
    from setuptools import setup  # Always prefer setuptools over distutils
  File "/tmp/easy_install-3gup5eno/luckydonald-utils-0.43/luckydonaldUtils/dependencies/__init__.py", line 3, in <module>
  File "/tmp/easy_install-3gup5eno/luckydonald-utils-0.43/luckydonaldUtils/dependencies/install.py", line 2, in <module>
  File "/tmp/easy_install-3gup5eno/luckydonald-utils-0.43/luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>
ImportError: No module named 'pip.utils'
```

**Comment by luckydonald** [comment]
That should address that. Included in `luckydonald-utils` `v0.44` should work again.
