### ISSUE TITLE
fail to install luckydonald-utils through pip or manually

### ISSUE THREAD

**Issue by antigraviton** [luckydonald/luckydonald-utils#4]
installing luckydonald-utils fails through pip install but also manually with git clone followed by python setup.py install:

The log:

```
pip install luckydonald-utils
Downloading/unpacking luckydonald-utils
  Downloading luckydonald-utils-0.43.tar.gz
  Running setup.py egg_info for package luckydonald-utils
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/luckydonald-utils/setup.py", line 4, in <module>
        from luckydonaldUtils.dependencies import find_submodules
      File "luckydonaldUtils/dependencies/__init__.py", line 3, in <module>
        from .install import find_packages, import_or_install, import_only, find_submodules
      File "luckydonaldUtils/dependencies/install.py", line 2, in <module>
        from .pip_interface import pip_install
      File "luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>
        from pip.utils import get_prog
    ImportError: No module named utils
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/luckydonald-utils/setup.py", line 4, in <module>

    from luckydonaldUtils.dependencies import find_submodules

  File "luckydonaldUtils/dependencies/__init__.py", line 3, in <module>

    from .install import find_packages, import_or_install, import_only, find_submodules

  File "luckydonaldUtils/dependencies/install.py", line 2, in <module>

    from .pip_interface import pip_install

  File "luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>

    from pip.utils import get_prog

ImportError: No module named utils

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/luckydonald-utils
```

**Comment by luckydonald** [comment]
I think this was fixed in an update.

**Comment by luckydonald** [comment]
Also make sure you have a recent `pip` version.

**Comment by luckydonald** [comment]
probably fixed.
